### ISSUE TITLE
Question about value larger than 8 bytes

### ISSUE THREAD

**Issue by cwk08** [sfu-dis/pibench-ep2#14]
In the implementation of all trees' wrappers,  **value** part  is set as a 8 byte pointer. Why does all the test choose to use only 8 byte value?
I also found that In Pibench test, the actual value space will not be flushed into persistent memory. I want to know if it's necessary to persist the value space and consider it's  overhead for larger than 8 bytes value test?

**Comment by georgeh0214** [comment]
We choose 8-byte value as it is the default in pibench. In the experiments we focus more on the keys, to be specific their sizes, distribution and etc. Also for key value pairs that are stored together, flushing the key would automatically flush the value if they happen to reside on the same cacheline.
